#  * Store hashtags in a list. Remove duplicate hashtags while maintaining the original order.
hashtags = ['@harsh_24', '@tejasshah2k', '@shyammukharjee45',
            '@abhishekdoshi99', '@rahulkirpekar89', '@shyammukharjee45']


# * Store email addresses in a list. Print only the emails that end with "@gmail.com".
email_addresses = ['harshpatel4504@gmail.com', 'abhishekdoshi@outlook.com',
                   'tejasshah2k19@gmail.com', 'rahulkirpekar@skype.com']


#  * student records 1. Highest Average 2. Lowest Average  3. Topper Name
data = [
    "Amit,85,90,78",
    "Neha,92,88,95",
    "Rahul,75,80,70"
]


# highest_avg = 0
# lowest_avg = 0
# name = ""
# for d in data :
#     words = d.split(",")
#     print(words)
#     sum = 0
#     for i in range(1,4):
#         sum += int(words[i])

#     avg = sum / 3

#     if highest_avg < avg:
#         highest_avg = avg
#         name = words[0]

#     if lowest_avg == 0 or lowest_avg > avg:
#         lowest_avg = avg

# print("Highest Average :",highest_avg)
# print("Lowest Average :",lowest_avg)
# print("Topper name :",name)



#  * Library Management   1. Display only available books.

data = [
    "Python Basics-Available",
    "Java Fundamentals-Issued",
    "C Programming-Available"
]
